[package]
name = "texide-rule-sentence-length"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Texide rule: Check sentence length"

[lib]
crate-type = ["cdylib"]

[dependencies]
texide-rule-foundation = { workspace = true }
extism-pdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
