[package]
name = "tsuzulint-rule-no-doubled-joshi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "TsuzuLint rule: Detect repeated Japanese particles"

[lib]
crate-type = ["cdylib"]

[dependencies]
tsuzulint-rule-pdk = { workspace = true }
extism-pdk = { workspace = true }
serde = { workspace = true }
rmp-serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
