[package]
name = "tsuzulint-rule-pdk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Common types for TsuzuLint WASM rules"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rmp-serde = { workspace = true }
extism-pdk = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
